config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :resumes
  resource :users, except: %i[new destroy] do
    get "sign_up", action: "new"
    get "sign_in"
  end
  resource :session, only: %i[create destroy]
  get "/resumes/:id/edit", to: "resumes#edit", as: "edit_resumes"
  get "/resumes", to: "resumes#index"
  get "/resumes/new", to: "resumes#new"
  get "/resumes/:id", to: "resumes#show", as: "resume"
  delete "/resumes/:id", to: "resumes#destroy"
  patch "/resumes/:id", to: "resumes#update"
  post "/resumes", to: "resumes#create"
  root "pages#home"

  # get "/resumes/@:userid/:slug", to: "resumes#slug"

  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
  validates :name, :tel, presence: true
  validates :email,
            presence: true,
            format: {
              with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
              message: "only email letters"
            }
  acts_as_paranoid

  def self.seach(keyword)
    where("name like ?", "%#{keyword}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :encrypt_password

  validates :password, presence: true, confirmation: true
  validates :email,
            presence: true,
            uniqueness: {
              message: "already exists"
            },
            format: {
              with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
              message: "only email letters"
            }

  private

  class << self
    def gender_list
      [["不公開", 0], ["男", 1], ["女", 2], ["其它", 3]]
    end

    def login(email:, password:)
      encrypted_password = Digest::SHA1.hexdigest("7a#{password}9x")
      find_by(email: email, password: encrypted_password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  helper_method :user_signed_in?, :current_user

  private

  def record_not_found
    # render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    render file: Rails.root.join("public", "404.html"),
           layout: false,
           status: :not_found
  end
  def user_signed_in?
    session[:_user_resume_dev_].present?
  end

  def current_user
    return User.find_by(id: session[:_user_resume_dev_]) if user_signed_in?

    return nil
  end

  def authenticate_user!
    redirect_to sign_in_users_path if not user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
    
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :find_params, only: %i[edit update show destroy]
  before_action :authenticate_user!
  def index
    # user: 自己 1
    # company: 全部 2
    # staff: 全部 3
    # 搜索 lazy loading
    @resumes = Resume.order(create_at: :desc)
    @resumes = @resumes.seach(params[:keyword]) if params[:keyword].present?
    # @resumes = Resume.order(create_at: :desc)
    # debugger
  end
  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to root_path, notice: "建立履歷"
    else
      render :new
    end
  end
  def show
  end

  def edit
  end

  def update
    redirect_to @resume if @resume.update(resume_params)
  end

  def destroy
    redirect_to @resume if @resume.destroy
  end

  private

  def resume_params
    params.require(:resume).permit(
      :name,
      :email,
      :tel,
      :skill,
      :intro,
      :city,
      :education,
      :experience,
      :portfolio
    )
  end

  def find_params
    @resume = Resume.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user =
      User.login(
        email: params[:user][:email],
        password: params[:user][:password]
      )
    if user
      session[:_user_resume_dev_] = user.id
      redirect_to root_path, notice: "登入成功"
    else
      redirect_to sign_in_users_path, alert: "登入失敗"
    end
  end

  def destroy
    session[:_user_resume_dev_] = nil
    redirect_to root_path, notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "註冊成功"
    else
      render :new
    end
  end

  def sign_in
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :birthday,
      :gender
    )
  end

  private
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatDate(date)
    date.strftime("%Y/%m/%d")
  end

  #   def user_signed_in?
  #     session[:_user_resume_dev_].present?
  #   end

  #   def current_user
  #     return User.find_by(id: session[:_user_resume_dev_]) if user_signed_in?

  #     return nil
  #   end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>菜雞上工</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>">
  <%= render "shared/navbar"  %>
  <%= render "shared/flash" if flash.any?%>

 

  <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於我</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>聯絡</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/resumes/_form.html.erb
<%= render "shared/form/error_message", record: resume %>


<div class="basic-grey">
<h1>履歷表
   <span>Please fill all the texts in the fields.</span>
</h1>
<%= form_for resume do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    
    <br>
    <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <br>
    <div class="field">
        <%= f.label :tel %>
        <%= f.telephone_field :tel %>
    </div>
    <br>
    <div class="field">
        <%= f.label :skill %>
        <%= f.text_field :skill %>
    </div>
    <br>
    <div class="field">
        <%= f.label :intro %>
        <%= f.text_area :intro %>
    </div>
    <br>
    <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city %>
    </div>
    <br>

    <div class="field">
        <%= f.label :education %>
        <%= f.text_area :education %>
    </div>
    <br>
    <div class="field">
        <%= f.label :experience %>
        <%= f.text_area :experience %>
    </div>
    <br>
    <div class="field">
        <%= f.label :portfolio %>
        <%= f.text_area :portfolio %>
    </div>
    <br>
    <%= f.submit class:"button" %>
<% end %>
</div>

app/views/resumes/_resume.html.erb
<section class="resume-container" >
<% @resumes.each do | resume |%>
    <section class="resume-card">
        <header class="cover"><img src="https://picsum.photos/500/550" alt=""></header>
            <section class="info">
                <div class="basic-info">
                    <h2 class="username"><%= resume.name %></h2>
                    <address class="location"><%= resume.city %></address>
                </div>
                <article class="intro">
                    <%= link_to resume.intro&.truncate(50), resume_path(resume) %>
                </article>            
            </section>
        <footer>
            <div class="update">更新時間: <%= formatDate(resume.updated_at)%></div>

            <div class="functions">
            <%= link_to "編輯", edit_resumes_path(resume), class: 'btn' %>
            <%= link_to "建立副本", 'model', class: 'btn'  %>
            <%= link_to "刪除", resume_path(resume), class: 'btn', method: 'delete', data: { confirm: 'Are you sure?' }  %>
            
            
            </div>
        </footer>
    </section>
<% end %>

</section>

app/views/resumes/edit.html.erb
<h1>新增履歷</h1>


<%
=begin%>
 <%= render "shared/form/error_message", record: @resume %> 
<%
=end%>

<%= render "form", resume: @resume %>

app/views/resumes/index.html.erb
<h1>履歷列表</h1>
<form  method="get">
    <input type="text" name="keyword" value="<%= params[:keyword] %>" id="" placeholder="請輸入關鍵字...">
    <input type="submit" value="送出">
</form>


<%= link_to "新增履歷", resumes_new_path %>
<%
=begin%>
 <%= render partial: "resume", collection: @resumes %> 
<%
=end%>
<%= render @resumes %>

app/views/resumes/new.html.erb
<h1>新增履歷</h1>

<%= render "form", resume: @resume %>

app/views/resumes/show.html.erb
<%= link_to "回到履歷列表", resumes_path %>

<h1><%= @resume.name %>的履歷</h1>

app/views/shared/_flash.html.erb
     <%  [:notice, :alert].each do |t| %>
        <% if flash[t] %>
            <div class="flash">
                <%= flash[:notice] %>
            <button>X</button>
            </div>
        <% end %>
    <% end %>

app/views/shared/_navbar.html.erb
 <nav class="navbar">
    
    <%
=begin%>
 <%= link_to "首頁", root_path %> 
<%
=end%>
 <a class="logo" href="/">
      <%= image_pack_tag "logo.png" %>
    </a>
  <ul>
   <% if user_signed_in? %>
      <li><%= current_user.email %></li>
      <li><%= link_to '登出', sessions_path, method: 'delete' %></li>
    <% else %>
      <li><%= link_to '註冊', sign_up_users_path %></li>
      <li><%= link_to '登入', sign_in_users_path %></li>
    <% end %>
  <li>
    <%= link_to "履歷列表", resumes_path %>
  </li>
  <li>
    <%= link_to "關於", about_path %>
  </li>
  <li>
    <%= link_to "聯絡", contact_path %>
  </li>
  </ul>


  </nav>

app/views/shared/form/_error_message.html.erb
<% if record.errors.any? %>
    <section class="error-message">
    <% record.errors.full_messages.each do |msg| %>
        <ul>
            <li><%= msg %></li>
        </ul>
    <% end %>
    </section>
<% end %>

app/views/users/new.html.erb
<h1>註冊</h1>

<div class="basic-grey">
    <%= form_with(model: @user) do |f| %>
        <div class="field">
            <%= f.label :email, 'Email 信箱' %>
            <%= f.email_field :email %>
        </div>
        <div class="field">
            <%= f.label :password, '密碼' %>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation, '密碼確認' %>
            <%= f.password_field :password_confirmation %>
        </div>
        <div class="field">
            <%= f.label :birthday, '生日' %>
            <%= f.date_field :birthday, max: 15.years.ago, min: 100.years.ago %>
        </div>
        <div class="field">
            <%= f.label :gender, '性別' %>
            <%= f.select :gender , User.gender_list %>
        </div>



        <hr>
        <div class="field">
        <%= f.submit '註冊', class: "button"%>
        </div>
  <% end %>  
</div>

app/views/users/sign_in.html.erb
<h1>登入</h1>

<%= form_with(model: @user, url: sessions_path) do |f| %>

  <div class="field">
    <%= f.label :email, 'Email 信箱' %>
    <%= f.email_field :email%>
  </div>

  <div class="field">
    <%= f.label :password, '密碼' %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit '登入' %>
<% end %>